server {
    listen 80;
    listen [::]:80;
    server_name vnux.com.br www.vnux.com.br;
    
    # Redireciona tudo para o HTTPS do .tech
    location / {
        return 301 https://vnux.tech$request_uri;
    }
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name vnux.com.br www.vnux.com.br;

    # Usa o certificado do .com.br para aceitar a conexão com segurança antes de redirecionar
    ssl_certificate /etc/nginx/certs/vnux.com.br.crt;
    ssl_certificate_key /etc/nginx/certs/vnux.com.br.key;

    # Redireciona tudo para o .tech
    location / {
        return 301 https://vnux.tech$request_uri;
    }
}
